site: marjz

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slug
  projects:
    output: true
    permalink: /project/:slug
  fronts:
    output: true
    permalink: /front/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  -
    scope:
      path: ""
      type: "fronts"
    values:
      layout: "front"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 40
paginate_path: "/blog/page:num/"

grid_alignments:
  - top
  - center
  - bottom

# my additions:

future: true #future posts are published in blog

exclude:
  - vendor/
# recommended here: https://livid.v2ex.com/guides/2023/01/03/jekyll-macos-ventura.html
