basic_settings:
  site_title: _Martin Zeilinger
  favicon_image: /images/favicon.png

header_settings:
  logo_image:
  logo_width: 200

menu_settings:
  menu_items:
    #- title: '_projects'
    #  url: '/'
    #- title: '_contact'
    #  url: '/contact'
    # - title: '_test'
    #  url: '/test'
    - title: '_about'
      url: '/about'
    - title: '_news'
      url: '/news-list' #was /news/ to refer to grid thing of news…
    - title: '_writing'
      url: '/writing-list' #was /writing/ to refer to grid thing of writing… create page here that uses blog format but displaying only the writing category!
    - title: '_curatorial'
      url: '/curatorial'
    - title: '_teaching'
      url: '/teaching'
    - title: '_all'
      url: '/'
    # - title: '_projects'
    #  url: '/'
    - title: '_front' # renamed from blog
      url: '/front/front' # url: '/blog/' #must be changed to root when it's the main site...

footer_settings:
  footer_tagline: MZ tinkering with Ruby/Liquid/YAML/Sass/Git/etc. in Jekyll.

grid_settings:
  overlay_opacity: 0.9
  grid_spacing: 10
  content_alignment: bottom

contact_settings:
  form_action: 'https://formspree.io/marjz.forward@gmail.com'
  confirmation_url: '/thanks'
  email_subject: 'Contact form submission'
  send_button_text: 'Send Message'

social_settings:
  facebook_url: ''
  twitter_url: 'https://twitter.com/mrtnzlngr'
  instagram_url: ''
  snapchat_url: ''
  youtube_url: ''
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: ''
  quora_url: ''
  amazon_url: ''
  apple_url: ''
  android_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  deviantart_url: ''
  github_url: 'https://github.com/st01c'
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: ''
  bandcamp_url: ''
  linkedin_url: ''

color_settings:
  background_color: '#ffffff' # site background #'#ededed' #(light grey)
  background_alt_color: '#f4f5f6' # ??
  text_dark_color: '#2A2F36'
  text_medium_color: '#363d44' #'#6C7A89'
  text_light_color: '#ABB7B7'
  accent_color: '#ff0718' #'#4ecdc4' # link hover highlight, link underline, and highlight in nav
  border_color: '#dddddd'
  overlay_background_color: 'yellow' #'#5f678c' #'yellow' #'#DCDCDC' #'#669999' #'#4ecdc4' # grid hover color #THIS AFFECTS
  grid_overlay_color: 'grey' #trying this so that it's used only for main page grid overlay…
  overlay_text_color: '#000000' #'#ffffff' # grid item text color
  overlay_accent_color: '#2A2F36' # ??
  error_color: '#D64541'
  hover-link-color: 'ffffff'

font_settings:
  font_embed: '<link href="https://fonts.googleapis.com/css?family=Poppins:300,500" rel="stylesheet">'
  #font_embed: '<link href="https://fonts.googleapis.com/css?family=Old+Standard+TT" rel="stylesheet">'
  #font_embed: '<link href="https://fonts.googleapis.com/css?family=Merriweather" rel="stylesheet">'
  title_font: '"Poppins", sans-serif'
  body_font: '"Poppins", sans-serif'
  #menu_font:

  #title_font: '"Old+Standard+TT", serif'
  #body_font: '"Old+Standard+TT", serif'
  #title_font: '"Merriweather", serif'
  #body_font: '"Merriweather", serif'
  regular_weight: 300
  bold_weight: 500
  site_title:
    small_size: 22
    medium_size: 26
    large_size: 30
    weight: 400 #500
    letter_spacing: -0.01
  menu:                         # menu fonts
    small_size: 20
    medium_size: 20 #17
    large_size: 20 #17 #15
    weight: 300
    letter_spacing: 0
  grid_item_title:
    small_size: 13 #15 #22
    medium_size: 24
    large_size: 25 #28
    weight: 400 #500
    letter_spacing: -0.02
  grid_item_subtitle:
    small_size: 11
    medium_size: 15
    large_size: 17
    weight: 300
    letter_spacing: 0
  h1:
    small_size: 25 #25
    medium_size: 30 #35
    large_size: 35 #45
    weight: 500
    letter_spacing: -0.02
    line_height: 1.2
  h2:
    small_size: 22
    medium_size: 30
    large_size: 35
    weight: 500
    letter_spacing: -0.02
    line_height: 1.2
  h3:
    small_size: 22
    medium_size: 25
    large_size: 30
    weight: 500
    letter_spacing: -0.02
    line_height: 1.3
  h4:
    small_size: 17
    medium_size: 22
    large_size: 22
    weight: 500
    letter_spacing: 0
    line_height: 1.6
  h5:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 500
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 500
    letter_spacing: 0
    line_height: 1.6
  p:
    small_size: 16 #15
    medium_size: 18 #17
    large_size: 19 #16 #17 #19
    weight: 300
    letter_spacing: 0
    line_height: 1.3 #1.6
  blockquote:
    small_size: 16 #17 #25
    medium_size: 18 #20 #35
    large_size: 20 #25 #45
    weight: 300
    letter_spacing: -0.02
    line_height: 1.4
  buttons:
    weight: 500
    letter_spacing: 0

advanced_settings:
  ajax_loading: true
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""
